---
title: "R install packages"
output:
  html_document:
    df_print: paged
---

#hei

## Packages we will need

We set some options to make sure that we include dependencies and also that we install pre-compiled binaries. 

I’m sure we’ll have forgotten some, but we’ll install them when needed.

```{r}
install.packages("tidyverse", dependencies = TRUE, type="binary", repos='http://cran.uib.no')
install.packages("modelr", dependencies = TRUE, type="binary", repos='http://cran.uib.no')
install.packages("readr", dependencies = TRUE, type="binary", repos='http://cran.uib.no')
install.packages("huxtable", dependencies = TRUE, type="binary", repos='http://cran.uib.no')
# To be used to set up git/github
install.packages("usethis", dependencies = TRUE, type="binary", repos='http://cran.uib.no')
install.packages("credentials", dependencies = TRUE, type="binary", repos='http://cran.uib.no')
install.packages("styler", dependencies = TRUE, type="binary", repos='http://cran.uib.no')
# For packages not on CRAN we need devtools
install.packages("devtools", dependencies = TRUE, type="binary", repos='http://cran.uib.no')
# Install from github instead of CRAN
devtools::install_github('Timag/imageclipr', type="binary")
```

```{r}
#siste
```

